{
	"version": 1546162939,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/set3_background-sheet0.png",
		"images/set3_tiles-sheet0.png",
		"images/set3_hills-sheet0.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/jono-sheet0.png",
		"images/jono-sheet1.png",
		"images/tilegreen_-sheet0.png",
		"images/tilegreen_-sheet1.png",
		"images/sprite-sheet0.png",
		"images/tilegreen_2-sheet0.png",
		"images/tilegreen_3-sheet0.png",
		"images/tilegreen_4-sheet0.png",
		"images/tilegreen_4-sheet1.png",
		"images/tilegreen_5-sheet0.png",
		"images/tilegreen_6-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/score.png",
		"images/head_focus-sheet0.png",
		"images/nagor_besar-sheet0.png",
		"images/enemywalking_-sheet0.png",
		"images/enemywalking_-sheet1.png",
		"images/enemywalking_-sheet2.png",
		"images/enemyswimming_-sheet0.png",
		"images/player_hurt-sheet0.png",
		"images/bendera-sheet0.png",
		"images/play_title-sheet0.png",
		"images/title_depan-sheet0.png",
		"images/mulai-sheet0.png",
		"images/spritefont.png",
		"images/intro-sheet0.png",
		"images/intro2-sheet0.png",
		"images/intronasigoreng-sheet0.png",
		"images/nagor-sheet0.png",
		"images/nagor-sheet1.png",
		"images/nagor-sheet2.png",
		"images/introbaksoberanak-sheet0.png",
		"images/baso-sheet0.png",
		"images/baso-sheet1.png",
		"images/baso-sheet2.png",
		"images/pizza-sheet0.png",
		"images/pizza-sheet1.png",
		"images/pizza-sheet2.png",
		"images/intropizza-sheet0.png",
		"images/gameoverend-sheet0.png",
		"images/button_14copy-sheet0.png",
		"images/keluar-sheet0.png",
		"images/finish-sheet0.png",
		"images/spritefont5.png",
		"images/desawekwek-sheet0.png",
		"images/gangbuntu-sheet0.png",
		"images/kotatua-sheet0.png",
		"images/set2_background-sheet0.png",
		"images/set2_hills-sheet0.png",
		"images/set2_tiles-sheet0.png",
		"images/intro3-sheet0.png",
		"images/desawekwek2-sheet0.png",
		"images/gangbuntu2-sheet0.png",
		"images/kotatua2-sheet0.png",
		"images/gameover-sheet0.png",
		"images/finish2-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/collect key.m4a",
		"media/collect key.ogg",
		"media/enemyhit.m4a",
		"media/enemyhit.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}